---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - url: "/users/74776/articles/165663/master/file/figures/19-Table3-1/19-Table3-1.png"
    path: figures/19-Table3-1/19-Table3-1.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
